
export const ADD_CATEGORY = 'CATEGORY.ADD';
export const SAVE_CATEGORY = 'CATEGORY.SAVE';
export const CLOSE_CATEGORY_FORM = 'CATEGORY.FORM.CLOSE';
export const DELTE_CATEGORY = 'CATEGORY.DELTE';
export const SET_CATEGORY = 'CATEGORY.SET';
export const EDIT_CATEGORY = 'CATEGORY.EDIT';

export const ADD_LOCATION = 'LOCATION.ADD';
export const SAVE_LOCATION = 'LOCATION.SAVE';
export const CLOSE_LOCATION_FORM = 'LOCATION.FORM.CLOSE';
export const DELTE_LOCATION = 'LOCATION.DELTE';
export const SET_LOCATION = 'LOCATION.SET';
export const EDIT_LOCATION = 'LOCATION.EDIT';
export const SHOW_MAP = 'LOCATION.SHOW.MAP';


